# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      -run:
          name: Install npm dependencies
          command: npm install
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: cd learn-express && npm run test
      - run:
          name: Run Tests with Coverage
          command: cd learn-express && npm run test:ci

  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: npm run dev
      - store_artifacts:
          path: learn-express/dist
  # deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - test
