# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env: 
    TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
    CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
    CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
    CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
    
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: cd learn-express && npm ci
    - name: Build
      run: cd learn-express && npm run build --if-present
    - name: Test
      run: cd learn-express && npm test